services:
  mongo:
    image: mongo
#    ports:
#      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./data/mongo:/data/db
  redis:
    image: redis
#    ports:
#      - 6379:6379
    volumes:
      - ./data/redis:/data
    command: ['redis-server', '--appendonly', 'yes']
  server:
    image: todo-backend-dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
